field: 3fff2238-67a0-4baf-afcf-9136097514c6 # Body
fieldLayouts:
  ed6dd3c8-a486-4fba-a00c-a6bc6ca097df:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f69e6ee9-ff7b-4eaa-84f0-d2ff99875703 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79d8dcb4-12a8-4d7d-a05a-4606791f9101
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 335d9f3f-fd3d-4d5c-85cc-2869bbab079d # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 538c855e-665d-478b-99ca-f3b7801ad52a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 59e92d22-da34-4e49-9c75-a272bc8e9ac0 # CTAs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 691bdea2-00ca-403d-8b36-130e84206782
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 22dcebcf-5e09-4732-b922-4973a5557508
        userCondition: null
fields:
  59e92d22-da34-4e49-9c75-a272bc8e9ac0: # CTAs
    columnSuffix: xoxzhotr
    contentColumnType: text
    fieldGroup: null
    handle: ctas
    instructions: null
    name: CTAs
    searchable: false
    settings:
      addRowLabel: 'Add CTA'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Text
                -
                  - handle
                  - text
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - URL
                -
                  - handle
                  - url
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults: null
      maxRows: 1
      minRows: 0
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
  335d9f3f-fd3d-4d5c-85cc-2869bbab079d: # Text
    columnSuffix: amdruodw
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f69e6ee9-ff7b-4eaa-84f0-d2ff99875703: # Theme
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 0
      selectionLabel: 'Select theme'
      showSiteMenu: false
      source: 'group:84abf42b-4f2b-48ba-8f3d-12a0b7cc81d5' # Themes
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
handle: simpleText
name: 'Simple text'
sortOrder: 5
