field: 3fff2238-67a0-4baf-afcf-9136097514c6 # Body
fieldLayouts:
  edda55c6-2ebc-4f44-8a32-2e0806db26ce:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9d562cf3-1231-4c00-812b-7ffeee186f40 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f762e984-0b70-4dbe-9f4b-96c92be2204a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f76704a8-1e0a-452c-b238-06c89c9f99ab # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcd47258-75cf-4f90-9fe1-8833d55b8fac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0dcac99b-80d8-400f-bdf3-03077ececd2d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6675eaf-1a79-425d-80a8-4973f7ac7ce6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a7a87b13-087a-425b-81b5-6844975e7ff8 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6eb7be92-33ed-4789-985d-90979e3cb181
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7e94c4b3-3d22-4fe7-9585-137c97994807 # Text position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 449a990e-ab9a-4e72-bc99-09354b0f77f0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7c52c4b9-426b-4e12-bbfc-3fa09b93360e # Media placement
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 228c1db3-b713-458d-b8c9-6708cb3b1066
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e8d6aeb-abf5-4da6-af23-c84b3dc8bf34 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26d0ef42-a1d4-48ba-8703-fc633f1652e7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 368a16e6-21f3-4787-9d83-f5dba4cadf05 # Parallax scroll effect?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5863d07-d0fc-4108-bb4b-5337df3c5636
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a7e02d9a-abd3-449d-abe2-5a7e9c7dde25 # Embed HTML
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 586425f9-e011-4818-93f1-e1ead2cecdd8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f8cebeb1-c830-436d-9fb5-5ec881581221 # Embed aspect ratio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7139d21-3b40-4f39-9336-45c7724cb081
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1f88abed-353d-4126-989e-9c4fe2c19737 # CTAs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1a69b1d-f07a-4e06-bf7e-0c27ecc3d43f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 53356f3d-f783-4b56-a903-e058f5b09b5f
        userCondition: null
fields:
  0dcac99b-80d8-400f-bdf3-03077ececd2d: # Heading
    columnSuffix: sgcguvvp
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  1f88abed-353d-4126-989e-9c4fe2c19737: # CTAs
    columnSuffix: lbadmcoi
    contentColumnType: text
    fieldGroup: null
    handle: ctas
    instructions: null
    name: CTAs
    searchable: false
    settings:
      addRowLabel: 'Add CTA'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Text
                -
                  - handle
                  - text
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - URL
                -
                  - handle
                  - url
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - 'Primary?'
                -
                  - handle
                  - isPrimary
                -
                  - width
                  - ''
                -
                  - type
                  - lightswitch
      defaults: null
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
  3e8d6aeb-abf5-4da6-af23-c84b3dc8bf34: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
        - video
      branchLimit: null
      defaultUploadLocationSource: 'volume:254d3d32-c63f-4944-bb6d-9a5bdac19b4b' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 0
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:254d3d32-c63f-4944-bb6d-9a5bdac19b4b' # Images
      restrictedLocationSubpath: text-media
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Select image'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  7c52c4b9-426b-4e12-bbfc-3fa09b93360e: # Media placement
    columnSuffix: ncwnwlfp
    contentColumnType: string
    fieldGroup: null
    handle: mediaPlacement
    instructions: null
    name: 'Media placement'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Float
            -
              - value
              - float
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Cover
            -
              - value
              - cover
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  7e94c4b3-3d22-4fe7-9585-137c97994807: # Text position
    columnSuffix: mlyqtuaz
    contentColumnType: string
    fieldGroup: null
    handle: textPosition
    instructions: null
    name: 'Text position'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  9d562cf3-1231-4c00-812b-7ffeee186f40: # Theme
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 0
      selectionLabel: 'Select theme'
      showSiteMenu: false
      source: 'group:84abf42b-4f2b-48ba-8f3d-12a0b7cc81d5' # Themes
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  368a16e6-21f3-4787-9d83-f5dba4cadf05: # Parallax scroll effect?
    columnSuffix: jpupxpnz
    contentColumnType: boolean
    fieldGroup: null
    handle: isParallax
    instructions: 'Enabling this will make the image or embed scroll by at a lower speed, creating a parallax effect.'
    name: 'Parallax scroll effect?'
    searchable: false
    settings:
      default: false
      offLabel: 'No'
      onLabel: 'Yes'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  a7a87b13-087a-425b-81b5-6844975e7ff8: # Text
    columnSuffix: adkijwqt
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes:
        - 254d3d32-c63f-4944-bb6d-9a5bdac19b4b # Images
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Custom.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  a7e02d9a-abd3-449d-abe2-5a7e9c7dde25: # Embed HTML
    columnSuffix: bwbcqpxe
    contentColumnType: text
    fieldGroup: null
    handle: embedHtml
    instructions: null
    name: 'Embed HTML'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f8cebeb1-c830-436d-9fb5-5ec881581221: # Embed aspect ratio
    columnSuffix: eekghedj
    contentColumnType: string
    fieldGroup: null
    handle: embedAspectRatio
    instructions: null
    name: 'Embed aspect ratio'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - '16:9'
            -
              - value
              - 16x9
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - '4:3'
            -
              - value
              - 4x3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - 1x1
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f76704a8-1e0a-452c-b238-06c89c9f99ab: # Eyebrow
    columnSuffix: pdsjzbxr
    contentColumnType: text
    fieldGroup: null
    handle: eyebrow
    instructions: null
    name: Eyebrow
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: textMedia
name: 'Text & Media'
sortOrder: 7
