field: 3fff2238-67a0-4baf-afcf-9136097514c6 # Body
fieldLayouts:
  9cda3ffb-6963-4160-a11d-2a3d4f575b9c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: af0f230c-8c47-4726-873c-6f20638f2259 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27ce0067-2149-4f6a-950d-58ede3b4b265
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b3101e9-17fd-4d3a-a9ae-34f009753bd5 # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dda29f45-da53-4d1c-8030-16aefab72715
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a649e90b-4a92-4803-8103-bd91e9b552ff # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6225cf9-c09d-4569-8544-4f65d26f4fc4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3fa4ede3-631d-4efb-990a-d342df9724bf # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9ce49a3-1f15-4073-836a-20a8ace8755d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b26dd65b-e4f0-477c-a48f-377a9fdb98e9 # CTAs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c037507-e890-4fda-a947-1bd4c657b4fe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 658936bd-59e7-4e2a-9a4f-7811a4e9270d
        userCondition: null
fields:
  3b3101e9-17fd-4d3a-a9ae-34f009753bd5: # Eyebrow
    columnSuffix: cloeybje
    contentColumnType: text
    fieldGroup: null
    handle: eyebrow
    instructions: null
    name: Eyebrow
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3fa4ede3-631d-4efb-990a-d342df9724bf: # Text
    columnSuffix: iyiicsqv
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Custom.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  a649e90b-4a92-4803-8103-bd91e9b552ff: # Heading
    columnSuffix: oxmncjxu
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  af0f230c-8c47-4726-873c-6f20638f2259: # Theme
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 0
      selectionLabel: 'Select theme'
      showSiteMenu: false
      source: 'group:84abf42b-4f2b-48ba-8f3d-12a0b7cc81d5' # Themes
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  b26dd65b-e4f0-477c-a48f-377a9fdb98e9: # CTAs
    columnSuffix: iubagjvy
    contentColumnType: text
    fieldGroup: null
    handle: ctas
    instructions: null
    name: CTAs
    searchable: false
    settings:
      addRowLabel: 'Add CTA'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Text
                -
                  - handle
                  - text
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - URL
                -
                  - handle
                  - url
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - 'Primary?'
                -
                  - handle
                  - isPrimary
                -
                  - width
                  - ''
                -
                  - type
                  - lightswitch
      defaults: null
      maxRows: null
      minRows: 0
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: text
name: Text
sortOrder: 6
