columnSuffix: bebobcdx
contentColumnType: text
fieldGroup: 1f0cfe39-4ba4-4415-9a88-d4f5dc3f11df # Contact
handle: contactAddress
instructions: null
name: Address
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
