columnSuffix: ulujrslr
contentColumnType: boolean
fieldGroup: 1f0cfe39-4ba4-4415-9a88-d4f5dc3f11df # Contact
handle: contactIsPhoneSupportsWhatsapp
instructions: 'Schakel deze optie in wanneer u via WhatsApp bereikt kunt/wilt worden op dit nummer.'
name: 'Telefoonnummer ondersteunt WhatsApp?'
searchable: false
settings:
  default: false
  offLabel: Nee
  onLabel: Ja
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
