columnSuffix: csnlelfg
contentColumnType: text
fieldGroup: e06d5210-b8bd-48ea-9cba-31445a25d231 # Donate
handle: donateText
instructions: null
name: Text
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: Simple.json
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\redactor\Field
