columnSuffix: ptffxnpb
contentColumnType: text
fieldGroup: 5030c100-01df-4677-897d-cb82c849dfff # People
handle: personCompanyUrl
instructions: null
name: 'Company URL'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'https://'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
