columnSuffix: hbegbodj
contentColumnType: text
fieldGroup: 83d5e6a0-451a-4e87-87ef-29a82f0cb074 # Socials
handle: socialUrls
instructions: null
name: URLs
searchable: false
settings:
  addRowLabel: 'URL toevoegen'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Platform
            -
              - handle
              - platform
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - Facebook
                    -
                      - value
                      - facebook
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Instagram
                    -
                      - value
                      - instagram
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - LinkedIn
                    -
                      - value
                      - linkedin
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - TikTok
                    -
                      - value
                      - tiktok
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Twitter
                    -
                      - value
                      - twitter
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - WhatsApp
                    -
                      - value
                      - whatsapp
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - YouTube
                    -
                      - value
                      - youtube
                    -
                      - default
                      - false
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - URL
            -
              - handle
              - url
            -
              - width
              - ''
            -
              - type
              - url
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Tonen in navigatie?'
            -
              - handle
              - isShowInNav
            -
              - width
              - ''
            -
              - type
              - lightswitch
  defaults: null
  maxRows: null
  minRows: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
