changedFieldIndicator: 726320264
field: dd5eba1d-3305-4fe7-bdc6-8127d16350e6 # Cards
fieldLayouts:
  30dec771-ecf7-49e0-8ef6-d37db66fd76b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4d8bbcc7-d9f8-4612-a192-de525fbcf941 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb4e88a9-5d76-4b74-bbbf-4ba6efb68a34
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 59d081d5-cd03-43df-bbd6-e234b893d957 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49c6a1e1-3c65-4eb6-91b5-863596deba01
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ef529d54-8ff7-4751-a83d-dbcb01b23595 # Image position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89c97079-fb37-4ee9-a404-2cdddcefee66
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 712b9330-141c-4892-8dbb-01b703461506 # Image is icon?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c02d05c4-f932-4042-9fb3-68cf281e4e31
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1c5e7d81-1eee-4876-ad6b-d4d8f61eec8a # Kop
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d452df74-896a-4b58-a670-f3c926fe83b1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a6a4b4c6-b08f-4905-8cc9-a11a097049ed # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 546b5236-3050-48a4-ae1a-23779fdf2a0d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: acc79d76-7a36-4da7-bc0f-c897bbd92200 # CTA tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9831306-ecac-4ff6-af64-27e29fe8cb74
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9e06412a-b5c9-4cfc-abaf-16a4b576787a # CTA URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8edbcc9-bd37-4c6f-a6e3-366a3130497d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56f538eb-89c8-4352-962f-6e0dc272dcf1 # CTA type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 894eece1-d5cc-4c6b-851d-a25a146b799f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3206bc0e-c660-4d6c-ade9-a6d4885041be # Text alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed7144b6-5e42-4691-b552-80baec2e3cd7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3d160834-fd20-4f54-ba59-e24c34dfd3a6
        userCondition: null
fields:
  1c5e7d81-1eee-4876-ad6b-d4d8f61eec8a: # Kop
    columnSuffix: uhesjrxs
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Kop
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  4d8bbcc7-d9f8-4612-a192-de525fbcf941: # Theme
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: theme
    instructions: null
    name: Theme
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 0
      selectionLabel: 'Select theme'
      showSiteMenu: false
      source: 'group:84abf42b-4f2b-48ba-8f3d-12a0b7cc81d5' # Themes
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  9e06412a-b5c9-4cfc-abaf-16a4b576787a: # CTA URL
    columnSuffix: sqpjgoda
    contentColumnType: text
    fieldGroup: null
    handle: ctaUrl
    instructions: null
    name: 'CTA URL'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  56f538eb-89c8-4352-962f-6e0dc272dcf1: # CTA type
    columnSuffix: bvowmszr
    contentColumnType: string
    fieldGroup: null
    handle: ctaType
    instructions: null
    name: 'CTA type'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Link
            -
              - value
              - link
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Button
            -
              - value
              - button
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Button (inverted)'
            -
              - value
              - button_inverted
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  59d081d5-cd03-43df-bbd6-e234b893d957: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:254d3d32-c63f-4944-bb6d-9a5bdac19b4b' # Images
      defaultUploadLocationSubpath: cards
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 0
      previewMode: full
      restrictFiles: false
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:254d3d32-c63f-4944-bb6d-9a5bdac19b4b' # Images
      restrictedLocationSubpath: cards
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Selecteer afbeelding'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  712b9330-141c-4892-8dbb-01b703461506: # Image is icon?
    columnSuffix: nodlzidy
    contentColumnType: boolean
    fieldGroup: null
    handle: isImageIcon
    instructions: null
    name: 'Image is icon?'
    searchable: false
    settings:
      default: false
      offLabel: 'No'
      onLabel: 'Yes'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  3206bc0e-c660-4d6c-ade9-a6d4885041be: # Text alignment
    columnSuffix: mzwfsomh
    contentColumnType: string
    fieldGroup: null
    handle: textAlignment
    instructions: null
    name: 'Text alignment'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Center
            -
              - value
              - center
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a6a4b4c6-b08f-4905-8cc9-a11a097049ed: # Body
    columnSuffix: hxvltaae
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: null
    name: Body
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  acc79d76-7a36-4da7-bc0f-c897bbd92200: # CTA tekst
    columnSuffix: ctwlljsh
    contentColumnType: text
    fieldGroup: null
    handle: ctaText
    instructions: null
    name: 'CTA tekst'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  ef529d54-8ff7-4751-a83d-dbcb01b23595: # Image position
    columnSuffix: sltwxglv
    contentColumnType: string
    fieldGroup: null
    handle: imagePosition
    instructions: null
    name: 'Image position'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Top
            -
              - value
              - top
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Bottom
            -
              - value
              - bottom
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
