fieldLayouts:
  de8297a9-e85e-4026-8b6e-4bd77d63794b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d6199efc-3ac4-4d43-81d9-337c93ffca4c # Visual
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c88ba248-5d0c-4fb9-9f2d-e3a7d9b69724
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 86432240-b00d-4c6d-a618-d78241f90e34 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71abd314-c111-4d5d-824c-c279b449f33b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 490c9aae-b785-421c-8809-ea1a407d3b83 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df5bd976-0597-424d-97bf-2cb643b8148e
            userCondition: null
            warning: null
            width: 100
        name: Donate
        uid: da93b86e-218a-4095-9615-115ca216442b
        userCondition: null
handle: donate
name: Donate
sortOrder: 6
