defaultPlacement: end
enableVersioning: false
handle: faq
name: FAQ
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: siteGroup
siteSettings:
  cc7cc153-c4ab-4663-a4fb-968ed21e196b: # English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 352f5a5e-3679-47c9-85df-d6d212c2930b
type: structure
