defaultPlacement: end
enableVersioning: false
handle: nav
name: Navigatie
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c64df7e3-a993-46f7-9510-fa4ac9bcff1e: # English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  cc7cc153-c4ab-4663-a4fb-968ed21e196b: # Nederlands
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 12020fab-c011-437b-b4b7-52be283b6d8f
type: structure
