defaultPlacement: end
enableVersioning: false
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c64df7e3-a993-46f7-9510-fa4ac9bcff1e: # ไทย
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{parent.slug}/{slug}'
  cc7cc153-c4ab-4663-a4fb-968ed21e196b: # English
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{parent.slug}/{slug}'
structure:
  maxLevels: null
  uid: 428b7896-1051-4ea7-949b-2fa7523a7516
type: structure
